services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file:
      - /opt/homelab-repo/stacks/media/.env
    volumes:
      - ${CONFIG_PATH}/jellyfin:/config
      - ${MEDIA_PATH}:/media
    ports:
      - "8096:8096"
    restart: unless-stopped
    networks:
      - media
    devices:
      - /dev/dri:/dev/dri

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - /opt/homelab-repo/stacks/media/.env
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${MEDIA_PATH}/tv:/tv
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - media

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - /opt/homelab-repo/stacks/media/.env
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${MEDIA_PATH}/movies:/movies
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped
    networks:
      - media

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    env_file:
      - /opt/homelab-repo/stacks/media/.env
    volumes:
      - ${CONFIG_PATH}/lidarr:/config
      - ${MEDIA_PATH}/music:/music
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - "8686:8686"
    restart: unless-stopped
    networks:
      - media

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    env_file:
      - /opt/homelab-repo/stacks/media/.env
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    networks:
      - media

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    restart: unless-stopped
    networks:
      - media
    environment:
      - LOG_LEVEL=${SEERR_LOG_LEVEL}
      - TZ=${TZ}
    ports:
      - "5055:5055"
    volumes:
      - /srv/docker/media/seerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    networks:
      - media
    ports:
      - "6767:6767"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /srv/docker/media/bazarr:/config
      - ${MEDIA_PATH}/movies:/movies
      - ${MEDIA_PATH}/tv:/tv

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    env_file:
      - /opt/homelab-repo/stacks/media/.env
    volumes:
      - ${CONFIG_PATH}/sabnzbd:/config
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - media

networks:
  media:
    name: media