services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    env_file:
      - /opt/homelab-repo/stacks/minecraft/.env
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: ${MINECRAFT_VERSION}
      MEMORY: ${MINECRAFT_MEMORY}
      SERVER_NAME: ${MINECRAFT_SERVER_NAME}
      ONLINE_MODE: "TRUE"
      ENABLE_WHITELIST: "TRUE"
    volumes:
      - ${CONFIG_PATH}/data:/data
    ports:
      - "25565:25565"
    restart: unless-stopped