services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    restart: unless-stopped
    extra_hosts:
      - "bobcat.internal:host-gateway"
    env_file:
      - .env
    ports:
      - "7575:7575"
    volumes:
      - ${CONFIG_PATH}:/appdata