all:
  children:
    homelab:
      hosts:
        bobcat:
          ansible_host: bobcat.home.arpa
        anole:
          ansible_host: anole.home.arpa
        hoverfly:
          ansible_host: hoverfly.home.arpa

    compute:
      hosts:
        bobcat:

    control:
      hosts:
        anole:

    monitoring:
      hosts:
        hoverfly:

    docker_hosts:
      hosts:
        bobcat:
        anole:
        hoverfly: