- name: Deploy homelab stacks
  hosts: Bobcat
  become: true

  vars:
    repo_path: /srv/git/homelab
    docker_path: /srv/docker

  tasks:

    - name: Pull latest repo
      git:
        repo: "https://github.com/JacksonTaylor2003/Homelab.git"
        dest: "{{ repo_path }}"
        update: yes
        force: yes

    - name: Sync stack definitions to runtime directory
      synchronize:
        src: "{{ repo_path }}/stacks/"
        dest: "{{ docker_path }}/"
        delete: yes
        recursive: yes

    - name: Find compose projects
      find:
        paths: "{{ docker_path }}"
        patterns: "docker-compose.yml"
        recurse: yes
      register: compose_files

    - name: Restart all compose stacks
      shell: |
        cd {{ item.path | dirname }}
        docker compose up -d
      loop: "{{ compose_files.files }}"